### ISSUE TITLE
[Feature Request] OpenInfo as default action

### ISSUE THREAD

**Issue by drinfernoo** [a4k-openproject/plugin.video.openmeta#11]
Requested by @lukehansford:

Can we please get the option added in the settings for OpenMeta so we can set it to default to Openinfo when we click an item.

This we can set Openmeta as widgets and when we click an item or show it will auto load the items in Openinfo.

You can set the default action in Kodi to default to information and not play but this messes up any other add-ons that don't use Openinfo.

**Comment by diabl0w** [comment]
> You can set the default action in Kodi to default to information and not play but this messes up any other add-ons that don't use Openinfo.

For me, even setting both kodi and skin's options to open info as default select action, this fails to occur with widgets for openmeta. In other words, if I open openmeta addon directly and browse for a movie title and select it, it correctly opens the openinfo dialog. However if I select that same movie title from a widget that was created pointing to the same openmeta page, openmeta just starts playing the movie. 

I think this has something to do with the fact that if you open the context menu for an openmeta widget, there is no item for "Information" while if you open the context menu inside openmeta itself there IS an "Information" context menu item. 

Hopefully I've described the issue clearly that it's easy to see what's going on. 

Same issue occurs in both Aura and BINGIE skins

**Comment by drinfernoo** [comment]
@diabl0w That and many other things related to the context menu should be fixed in coming updates to OpenMeta.

**Comment by diabl0w** [comment]
Great! Thanks for the great addon, it fills so many gaps for us users!

Just an update that the AuraMod skin does properly open extendedinfo from
openmeta widgets. It must handle widgets differently than Aura and Bingie
or something strange is going on. So I'll just stick with AuraMod for now
