### ISSUE TITLE
[Feature Request] Default Players

### ISSUE THREAD

**Issue by drinfernoo** [a4k-openproject/plugin.video.openmeta#14]
**Is your feature request related to a problem? Please describe.**
We'd like the ability to set a default player for media, so that the selector dialog only appears when chosen from the context menu.

**Describe the solution you'd like**
I believe a default player should be able to be set for each different type of media, from Settings. Then, that media would play from that player by default, unless the user chooses OpenMeta from the context menu, which would show all available players in a selector dialog.

**Comment by ProZeeshan** [comment]
This is a feature to have. I always use seren so there is no point in selecting it every time.

**Comment by drinfernoo** [comment]
Closed as of 042d5f9a05c56348e39f74d01a276f2e3faadf50.
