### ISSUE TITLE
[Bug] Add submenu to home menu

### ISSUE THREAD

**Issue by papadcha** [a4k-openproject/plugin.video.openmeta#17]
**Describe the bug**
When I add as home menu submenu item an entry from openmeta menu (for example Blockbusters Movies) and then open it from home menu it returns an error.

**To Reproduce**
1. Go to 'System/Skin Settings/Setup Aeon Nox Main Menu/'
2. Click on 'Movies/Select Submenu/Add/Choose item for menu/Add-on/Video Add-on/Openmeta/Blockbusters(TMDB)/Create menu item to here'
3. Retun to home menu select Movies/Bluckbusters(TMD)

**Expected behavior**
Open the menu of openmeta with blockbusters(TMDB) Movies

**Screenshots**
![Screen Shot 2019-04-15 at 10 07 23](https://user-images.githubusercontent.com/17113684/56113836-bf769280-5f67-11e9-88da-0937d33bc35f.png)

**Platform**
- Kodi version (18.1 Leia)
- Device (Mac)
- Operating System (MacOs El Capitan and Mojave)

**Log File**
Please attach a log file here. For information on how to retrieve your log file, check the [Kodi wiki](https://kodi.wiki/view/Log_file/Easy).

**Comment by drinfernoo** [comment]
This doesn't appear to be an issue any longer.
