### ISSUE TITLE
[Bug] duplicates in library

### ISSUE THREAD

**Issue by jaka87** [a4k-openproject/plugin.video.openmeta#18]
**Describe the bug**
On fresh installation I added Openmeta, and put some series into the library. After that I ran trakt to sync which episodes I have already watched. After that i see duplicate entries for episodes. I have also cleaned the library and tried without running trakt but the error is still persistent after some time. I remember this error was present with Metalliq some time ago and then fixed. It is not present in any other clones that i tried.

**Comment by disaacso** [comment]
two things, on first install it took my library about 24 hours to remove all duplicates so that may be something to wait for.  second, did you run total setup AND add a video source manually?  Total setup adds a video source automatically so that could be the issue if it persists

**Comment by jaka87** [comment]
Yes that was it. I didn't realize video source is added automatically.
