### ISSUE TITLE
[Addon ID with Capital Letters]

### ISSUE THREAD

**Issue by newf276** [a4k-openproject/plugin.video.openmeta#20]
Addons that use capital letters in the Add-on ID will not show up in the Player List.  Request capability to recognize Addons that use capital letters in the Add-on ID, so that they will show up in the player list.  Example of Addons with Capital letters do not work are Legendary Add-on, ReleaseBB Add-on and various others etc.

Of course the obvious alternative is for developers to not utilize capital letters.

Thanks

**Comment by JayDee696969** [comment]
Pretty sure thats more of a Kodi 18 issue, as they still work in 17 with capital letters.

**Comment by newf276** [comment]
Agreed you are correct. I guess that means there is three possible solutions, 1. Fix Kodi 18, 2. Fix OpenMeta, 3. Encourage the Add-on developer.  I assume might be easier to edit OpenMeta?

**Comment by JayDee696969** [comment]
Yea, it means these addon devs need to follow Kodi guidelines. It specifies in Kodi wiki: 
1.1.1 id attribute
The id attribute is the unique identifier used for this add-on. _**_It must be unique, and must use only lowercase characters, periods, underscores, dashes and numbers._**_ This identifier is also used as the name of the folder that contains the add-on, so for ease of searching, we suggest you use something like <type>.<uniquename>.

https://kodi.wiki/view/Addon.xml

**Comment by vitorp07** [comment]
@newf276 
JayDigg is absolutely correct, and if the addon developer(s) or maintainer(s) are not able to correct this and follow this simple rule then it is probably best to use different addons.
