### ISSUE TITLE
[Feature Request] Trakt context menu?

### ISSUE THREAD

**Issue by JayDee696969** [a4k-openproject/plugin.video.openmeta#21]
Since OpenMeta overrides the standard context menu, you cannot access Trakt options at all? Normally with the Trakt Context menu installed you can use all Trakt options from the context menu of almost all addons. 
So when using OpenMeta, how are we supposed to use Trakt at all? We cant add anything to Trakt, cant mark anything as watched/unwatched, add to collection/watchlist, rate, etc. Nothing. Seems all we can do is sync our current Trakt info and view it in My Trakt section?
Unless im missing something? 

**Describe the solution you'd like**
Add/allow Trakt options in context menus in Openmeta, preferably also in OpenInfo.

**Describe alternatives you've considered**
Only alternative I see is to add to library, then Sync Library with trakt? Then have to use Library to be able to edit any Trakt options?

**Additional context**
If Trakt integration was enabled it would be much easier i think to use OpenMeta/OpenInfo. Really wouldnt need Library at all.

For example, Seren has a built in Trakt manager via Context menu , so Doesnt even need the Kodi Trakt addon installed.

**Comment by shawngriffiths** [comment]
Any progress on adding a context menu for Trakt options to OpenMeta and OpenInfo? This would be a very helpful addition :)

**Comment by drinfernoo** [comment]
In the future, this will likely be implemented through OpenInfo.
