### ISSUE TITLE
[Feature Request] Context Menu - Include Download

### ISSUE THREAD

**Issue by mriksman** [a4k-openproject/plugin.video.openmeta#24]
Context menu from the Kodi Library has OpenInfo and OpenMeta added. What I'd like to see is a Download option. That way, from the main Kodi library, you can browse through and see what is tagged WEB (and therefore available only online) and can right-click and download for offline viewing. Either clicking by;
* Download from this Context menu loads the sources and you can select a source to download, or 
* add a context menu to the list of sources that appears when you try and play an episode (although this could be a Kodi limitation and you might not be able to load a separate context menu)

Currently, if I see an episode that is not available offline/locally, I need to open the Video Add-on, find the episode, load the sources, and then right-click and Download.

**Comment by drinfernoo** [comment]
OpenMeta doesn't at this time, and likely won't ever, handle downloads. It's simply outside of the scope of the add-on.

**Comment by mriksman** [comment]
Thanks for the feedback. Couldn't there be a way to call the Download action/command of the Add-on?

**Comment by SerpentDrago** [comment]
That would have to be added for every single addon supported . would be a major pain in the ass , and is very outside the scope of what the point of open meta is .  

I'm sure the player file could contain info on how to do this . but there is plenty of other things needed to be worked on before adding "extra features" such as this . 


Sorry , but dont' expect this anytime soon if ever .  I get the idea and its cool , its just wayy outside the scope
