### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by disaacso** [a4k-openproject/plugin.video.openmeta#37]
**Describe the bug**
update to 1.3.1 (might have been 1.3) broke some TV trakt lists.  In particular upcoming episodes is no longer accesable

**To Reproduce**
1. Go to TV shows > Trakt > upcoming episodes
2. Openmeta error is displayed

**Expected behavior**
Should get a menu showing upcoming episodes
**Screenshots**

**Platform**
- Kodi version (18.2)
- Device (libreelec, ubuntu boxes)

**Log File**
Not my log, but another persons with the same issue.
https://pastebin.com/pxsmV7wG

**Comment by SerpentDrago** [comment]
side note @disaacso , judgeing by the errors related to seren in that persons  log , you need to have that person with that log Reauth trakt in seren. and resync in trakt sync tools and reset database . just fyi ,  may even need to nice clean seren > tools > wipe , uninstall and reinstall and setup , tons of errors :)

as far as the issue with Openmeta , its being looked into , at first glance , it doesn't appear to be the latest update , so it may have been 1.3

**Comment by drinfernoo** [comment]
It appears this bug slipped past me when I merged #36... Which means 1.2.0 was the last working version, but is missing fanart.tv integration and the fix for widgets.

Currently working with @diddy81 to narrow down what went wrong.
