### ISSUE TITLE
[Bug] Episodes played with UpNext are not marked as "watched"

### ISSUE THREAD

**Issue by diabl0w** [a4k-openproject/plugin.video.openmeta#39]
**Describe the bug**
I am not sure if this is an issue with the UpNext addon or OpenMeta, but all  TV show episodes that are "autoplayed" via UpNext addon through OpenMeta are not properly marked as "watched"

**To Reproduce**
1. Install Up Next Addon and OpenMeta
2. Watch a TV Show episode in your library using OpenMeta
3. Do nothing to allow Up Next to trigger next episode to play through OpenMeta
4. Watch through entire episode or multiple entire episodes
5. When finished, only the original episode that you clicked on will be marked as watched

**Expected behavior**
All watched episodes should be marked as watched 

**Platform**
- Latest CoreELEC

**Comment by drinfernoo** [comment]
Neither Up Next or OpenMeta do any sort of Trakt scrobbling. This isn't an issue with OpenMeta, and likely not with Up Next either.

If it's local library content you'll need to use the Trakt add-on, but if you're watching streaming content from another video add-on, scrobbling would be up to that add-on.

**Comment by diabl0w** [comment]
@drinfernoo I am not referring to trakt... I am referring to Kodi's library watched status. Unless this has something to do with trakt that I don't know about. If I watch tv episodes in my library they have always gotten a watched checkmark whether using trakt or not

**Comment by diabl0w** [comment]
so if I use openmeta to watch an episode in my library (local library added there by syncing openmeta and trakt collection), what is controlling the local watch status? is it openmeta, trakt, or the addon that I choose in the openmeta dialog box?

**Comment by diabl0w** [comment]
@drinfernoo whatever it is that marks episodes as watched, nonetheless, I don't think its a config problem or anything on my end, because why would manually selected episodes be getting the correct watched status but autoplayed episodes not?

**Comment by drinfernoo** [comment]
@diabl0w For streaming sources, watched statuses (local or Trakt) are handled by the add-on which initiates playback. OpenMeta *does not* do either one.

I have a suspicion I know which add-on you're using with Up Next, and there is currently  known bug with that add-on not correctly scrobbling while Up Next integration is enabled.

This is not an OpenMeta issue.

**Comment by diabl0w** [comment]
okay thank you for the information
