### ISSUE TITLE
Choose which metadata to pull

### ISSUE THREAD

**Issue by hhoodd** [a4k-openproject/plugin.video.openmeta#40]
When I view a movie from a widget created from OpenMeta the [director info is blank,](https://imgur.com/a/jhU8zJX) but when I create a widget using other addons [the info is there](https://imgur.com/a/V04V0PG). Even on the same Trakt lists. An option to choose which metadata to grab would be great.

**Comment by drinfernoo** [comment]
This information simply isn't grabbed by OpenMeta. Sometime in the future, there's a possibility.

I also answered your thread on Reddit.
