### ISSUE TITLE
[Bug] trakt authentication broken

### ISSUE THREAD

**Issue by Instinctlol** [a4k-openproject/plugin.video.openmeta#42]
I cannot authenticate my trakt account in OpenMeta. When I press "Authenticate Trakt..." the dialog that mentions going to trakt.tv/activate is showing up nicely. When I authenticate OpenMeta on trakt.tv, the dialog stays up for a longer time (I don't know.. minutes?) and I cannot access my trakt collection from within OpenMeta.

I tried this on two devices, also tried it on a clean install.

**Comment by drinfernoo** [comment]
Can you provide a log file with this happening?

**Comment by Instinctlol** [comment]
Sure
[REMOVED LOGS]

**Comment by vitorp07** [comment]
@Instinctlol There is no indication about that error in those logs.
Can you [enable debug](https://kodi.wiki/view/Log_file/Easy#Steps), restart kodi, reproduce the error and upload a new debug log please?

**Comment by Instinctlol** [comment]
> @Instinctlol There is no indication about that error in those logs.
> Can you [enable debug](https://kodi.wiki/view/Log_file/Easy#Steps), restart kodi, reproduce the error and upload a new debug log please?

My bad.

Anyway, I tried it again. This time I
* enabled debug logging
* cleared trakt account settings
* clicked on "Authenticate Trakt..." and waited for like a minute until the dialog closed
* navigated to my trakt show collection and waited...
* while waiting, I got a new dialog asking me "Do you want to authenticate trakt now?" and went on with that procedure, the dialog closed faster this time
* renavigated to my trakt show collection and waited...
* it took a while, but now my shows are coming up. I then removed a show from my collection which didn't have any art (Royal Marines Mission Afghanistan)

Opening my collection is fast now.

I've attached the appropriate log, but I consider this issue solved.
[REMOVED LOGS]

**Comment by vitorp07** [comment]
@Instinctlol 
The error you had might of been due to a connection glitch while trying to reach trakt.tv to authenticate.

Thanks for posting the new log, you can edit your posts to delete them if you don't want anyone else to look at them.
