### ISSUE TITLE
[Feature Request] Please consider adding library option "Avoid creating duplicate content"

### ISSUE THREAD

**Issue by cg00001** [a4k-openproject/plugin.video.openmeta#44]
Few friends of mine had trouble with duplicate series on their libraries and I decided to  replicate their issue.

I added a series to my library with IT addon, used Trakt options / Synchronize library, and got my library full with my trakt series.

I added another show with OpenMeta and synchronized again and found out all series had duplicates.

It seems that IT addon has the "Avoid creating duplicate content" option but OpenMeta doesn't and it creates the duplicates.

Could you please add this feature?
![ksnip_20191010-220202](https://user-images.githubusercontent.com/38960370/66598846-a105f280-ebaa-11e9-9b1a-a8bba7473cbf.jpg)

**Comment by SOOTTV** [comment]
@cgcgcgcgcg You shouldn't use both. Just use OpenMeta. The "avoid creating duplicates" setting in addons doesn't work how you're expecting it to. If you use 2 addons that both have that setting there will most likely still be duplicates. At least thats my experience.

**Comment by cg00001** [comment]
> @cgcgcgcgcg You shouldn't use both. Just use OpenMeta. The "avoid creating duplicates" setting in addons doesn't work how you're expecting it to. If you use 2 addons that both have that setting there will most likely still be duplicates. At least thats my experience.

Thanks for your comment, still waiting for OpenMeta's dev response on that.

**Comment by dm2912** [comment]
> The "avoid creating duplicates" setting in addons doesn't work how you're expecting it to.

it works exactly as I expect. In "IT" if i use library from there it ignores things I have either in my local library, or in my netflix library and only brings over the additional things. If S01E05 of a certain show already exists either locally or in my netflix library then it does not add it to the IT library. 

The failing for me with Open Meta (And the sole reason I dont use it) is it duplicates everything I have in my local library.

**Comment by drinfernoo** [comment]
Unfortunately, this likely won't get added, as the developer has completely disappeared from the scene.
