### ISSUE TITLE
[Bug] OpenMeta does not work with shared Kodi MySql Library

### ISSUE THREAD

**Issue by stxtf** [a4k-openproject/plugin.video.openmeta#55]
**Describe the bug**
When adding a movie or TV show to a Kodi library that is shared from a central MySql database, nothing will happen.

The following is from the Kodi error log:

2019-11-21 12:04:16.051 T:2832  NOTICE: VideoInfoScanner: Starting scan ..
2019-11-21 12:04:16.051 T:2832  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
2019-11-21 12:04:42.189 T:3128 WARNING: Attempt to use invalid handle -1

**To Reproduce**
1. Installed clean version of Kodi
2. Install the latest version of OpenMeta, verify that it adds to the default local database
3. Create a clean shared Kodi Mysql database via advanced_settings.xml
4. Connect Kodi to that database
5. Movies and TV shows do not add to the shared database. Progress shows 0% for a second and then disappears.

**Expected behavior**
When the Kodi shared library is not used (simply by renaming advancedsettings.xml and restarting Kodi), OpenMeta can add movies and TV shows perfectly.

**Screenshots**

**Platform**
Kodi 18.4, 18.5
Windows PC

**Log File**
2019-11-21 12:04:16.051 T:2832  NOTICE: VideoInfoScanner: Starting scan ..
2019-11-21 12:04:16.051 T:2832  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
2019-11-21 12:04:42.189 T:3128 WARNING: Attempt to use invalid handle -1

**Comment by drinfernoo** [comment]
I do believe this is a Kodi limitation; adding to the shared library should be done on the host Kodi instance.

**Comment by stxtf** [comment]
It does work OK however using Exodus Redux- items added within Exodus Redux are added to the database and show up on other Kodis. Technically in my scenario there is no host Kodi, it is referencing a MariaDB server on the network.

**Comment by ruinernin** [comment]
@drinfernoo is right about this being a Kodi limitation. OpenMeta is not touching the database, it's creating directories with .strm and .nfo file which are then scanned by Kodi as normal. It looks like this is the issue.

**Comment by stxtf** [comment]
I just tried changing the OpenMeta Movies and TV directories to the Movies and TV directories created by Exodus Redux.

Now, OpenMeta can add shows and movies to my library without issue. Very odd.

**Comment by drinfernoo** [comment]
@stxtf Did you actually set the content for the OpenMeta sources?

**Comment by stxtf** [comment]
Yes, but I'm not sure if that changed when I switched to the shared library. Anyway, I figured it out. I set up a SMB server on the same device running the SQL server. Pointed both OpenMeta and Kodi library to that shared folder. Now everything works like a charm. Not a bug- just a user configuration error in the end.
