### ISSUE TITLE
Open Trakt widget slow

### ISSUE THREAD

**Issue by brentonv** [a4k-openproject/plugin.video.openmeta#59]
When I set my skin (Aura) to pull a Trakt widget from OpenMeta it can take up to 10 minutes to load. If I pull the same Trakt item from an addon such as Fen it loads in seconds?

The same applies in general when browsing directly in OpenMeta and this also happens regardless if I have set my own API's.

Is there anything known about this or something that can be done to speed it up?

Thanks for the great addon.

**Comment by ruinernin** [comment]
@brentonv I've been working on something to solve this issue with Trakt lists as widgets. It will call out to OpenMeta for playing and only supports movie lists at the moment. https://github.com/ruinernin/foxymeta

**Comment by Chup123** [comment]
@ruinernin is this a openmeta replacement or an helper for openmeta?

**Comment by brentonv** [comment]
Will await return of dev. Hope he comes back!!!
