### ISSUE TITLE
[Bug] Search taking 10-15 minutes to produce results

### ISSUE THREAD

**Issue by vitadome** [a4k-openproject/plugin.video.openmeta#62]
**Describe the bug**
I've tested all search methods, movies, tv via trakt and TMDB with extremely latent results or no results at all.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
- Kodi version (17.6 Krypton, 18.0 Leia, 18.1 Leia, etc...) 18.4
- Device (PC, Nvidia Shield, Mibox, Raspberry Pi, etc...) PC, Sony TV and Firestick
- Operating System (Android, WIndows, etc...) Android

**Log File**
Please attach a log file here. For information on how to retrieve your log file, check the [Kodi wiki](https://kodi.wiki/view/Log_file/Easy).

**Comment by drinfernoo** [comment]
Unfortunately, since there isn't a developer maintaining this project anymore, it may be worth finding a different add-on for your purposes. I find that TheMovieDb Helper by @jurialmunkey does a very good job of replicating OpenMeta *and* OpenInfo's functionality 👍

**Comment by vitadome** [comment]
Thanks so much for the quick reply.  I’ll look at that now!
