### ISSUE TITLE
[Bug] Issue with the last version of FEN

### ISSUE THREAD

**Issue by baltzis** [a4k-openproject/plugin.video.openmeta#70]
[kodi.log](https://github.com/a4k-openproject/plugin.video.openmeta/files/5646912/kodi.log)
**Describe the bug**
OpenMeta cannot handle the last version of FEN (v. 1.8.21) for TV shows. When trying to play any episode of any TV show using OpenMeta, the list of players appears correctly, but when selecting FEN to play, after a while an error notification is shown ("Fen error, see log ... etc."). However, this problem does not appear to concern movies. OpenMeta operates OK with them. Tests show that FEN works fine with TV shows when not triggered from within OpenMeta.

**To Reproduce**
1. Go to OpenMeta (Addons/Video)
2. Click on any TV show/episode
3. After the list of players opens, scroll down to Fen and select it
4. See the error notification

**Expected behavior**
FEN scrapers should be triggered showing the search process, and afterward the link list.

**Screenshots**

**Platform**
- Kodi 18.9 Leia
- PC and TVBox
- Operating System:(Android and Windows 10 (64bit)

**Log File**
Please attach a log file here. For information on how to retrieve your log file, check the [Kodi wiki](https://kodi.wiki/view/Log_file/Easy).

**Comment by drinfernoo** [comment]
Sounds like the player file for FEN needs to be updated.

**Comment by baltzis** [comment]
Thanks for the prompt response. I guess I'll have to wait for the next update.

**Comment by drinfernoo** [comment]
Player files are not maintained part of this project. Rather, they are separate: https://github.com/a4k-openproject/json.openplayers

Unfortunately, the OpenMeta players there tend to be pretty outdated, as this add-on isn't even in development anymore.
